name: Build and Release
on:
  push:
    tags:
      - "v*"  # 仅当推送标签时触发
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: macos-latest
            artifact_name: macos
            build_command: pyinstaller --onefile free_cursor.py
          - os: ubuntu-latest
            artifact_name: linux
            build_command: pyinstaller --onefile free_cursor.py
          - os: windows-latest
            artifact_name: windows
            build_command: pyinstaller --onefile free_cursor.py

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Build executable
        run: ${{
